#!/bin/bash

sudo ip addr add 10.1.1.2/24 dev tap-hal
sudo ip addr add 5000::2/64 dev tap-hal
sudo ip link set tap-hal up
sudo ip route add 100.64.0.0/16 via 10.1.1.1 dev tap-hal
sudo ip route add 10.0.0.0/24 via 10.1.1.1 dev tap-hal
sudo ip route add 10.1.2.0/24 via 10.1.1.1 dev tap-hal
sudo ip route add 10.1.3.0/24 via 10.1.1.1 dev tap-hal
sudo ip route add 10.1.4.0/24 via 10.1.1.1 dev tap-hal
sudo ip route add 10.1.5.0/24 via 10.1.1.1 dev tap-hal
sudo ip route add 2000::/64 via 5000::1 dev tap-hal
sudo ip route add 3000::/64 via 5000::1 dev tap-hal
sudo ip route add 4000::/64 via 5000::1 dev tap-hal
sudo ip route add 6000::/64 via 5000::1 dev tap-hal
